name: Automated Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress UI tests
        run: npx cypress run

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OWASP ZAP
        uses: zaproxy/action-full-scan@v1

      - name: Run ZAP security scan
        uses: zaproxy/action-full-scan@v1
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/'
          report: 'true'
