name: OWASP ZAP Baseline Scan

# This workflow will trigger on a push to any branch and on pull requests to main
on:
  push:
    branches:
      - '**'  # Trigger for pushes to all branches
  pull_request:
    branches:
      - main  # Trigger for pull requests to main

jobs:
  zap_scan:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWM2OTcxNmE2OGQ4MzAwMTMyNTg0OTQiLCJpYXQiOjE3MTEzMTYwMjJ9.tLs2z9hMybMoOageR_MJrO5JJf3isM7DMesLqfEklws
        docker_name: 'owasp/zap2docker-stable'  # Use the stable docker image
        target: 'https://thinking-tester-contact-list.herokuapp.com/'  # The target URL for the scan
